const e = "#deleted-channel",
    o = "Unknown User",
    t = {
        "app.title": "MEE6 - The Discord Bot",
        "app.description": "Install our Discord bot to set up leveling, moderation, music, Twitch, YouTube, and Reddit notifications for your Discord server.",
        "badge.new": "NEW",
        "badge.premium": "PREMIUM",
        "badge.limited": "LIMITED",
        "bottomCta.seeMore": "See more features",
        "button.add": "Add",
        "button.cancel": "Cancel",
        "button.create": "Create",
        "button.delete": "Delete",
        "button.edit": "Edit",
        "button.save": "Save",
        "button.update": "Update",
        "button.upgrade": "Upgrade",
        "button.yes": "Yes",
        "button.no": "Nope",
        "button.unlock": "Unlock",
        "changelog.title": "What's new?",
        "channelSelection.title": "Please select a channel...",
        "check.badWords": "Bad words",
        "check.duplicatedText": "Repeated text",
        "check.invites": "Server invites",
        "check.links": "External links",
        "check.manyCaps": "Excessive caps (70% > CAPS)",
        "check.massEmojis": "Excessive emojis",
        "check.massSpoilers": "Excessive spoilers",
        "check.massMentions": "Excessive mentions",
        "check.zalgo": "Zalgo",
        "checks.sanction.0": "Disabled",
        "checks.sanction.1": "Delete Message",
        "checks.sanction.2": "Warn Member",
        "checks.sanction.3": "Delete Message & Warn Member",
        "checks.ignored.channels": "Ignored Channels",
        "checks.allowed.roles": "Allowed Roles",
        "checks.allow.discordLinks": "Allow Discord links",
        "checks.allowed.websites": "Allowed Websites",
        "checks.badWords.list": "Bad Words List",
        "checks.addAWebsite.placeholder": "Add a website...",
        "checks.addAWord.placeholder": "Add a word...",
        "checks.emojis.threshold": "Emoji Limit",
        "checks.spoilers.threshold": "Spoiler Tags Limit",
        "checks.mentions.threshold": "Mentions Limit",
        "checks.ok.button": "OK",
        "checks.advanced.settings": "Settings",
        "command.action.heading": "Actions",
        "command.action.add.button": "Add action",
        "command.action.add.option.respond": "Reply with message",
        "command.action.add.option.send": "Send message",
        "command.action.add.option.addRoles": "Give Roles",
        "command.action.add.option.removeRoles": "Remove Roles",
        "command.action.title.add_roles": "Bot gives roles",
        "command.action.title.respond": "Bot responds with",
        "command.action.title.remove_roles": "Bot removes roles",
        "command.action.title.send": "Bot sends in channel",
        "command.add.message": "Add Message",
        "command.add.command": "Add Command",
        "command.allowedRoles.heading": "Allowed Roles",
        "command.allowedRoles.text": "Anyone with these roles can use this command. Adding @everyone means everyone!",
        "command.bannedRoles.heading": "Banned Roles",
        "command.bannedRoles.text": "Anyone with these roles can't use this command.",
        "command.bannedChannels.heading": "Banned Channels",
        "command.bannedChannels.text": "The command will not work in these channels.",
        "command.cooldown.heading": "Cooldown",
        "command.cooldown.text": "You can stop excessive use of this command by adding a user or server cooldown.",
        "command.cooldown.type.0.name": "No Cooldown",
        "command.cooldown.type.1.name": "User Cooldown",
        "command.cooldown.type.2.name": "Server Cooldown",
        "command.cooldown.duration.heading": "Cooldown Duration",
        "command.delete.confirmation": "Delete this command?",
        "command.default.description": "An awesome command!",
        "command.defaultAction.message": "Hey, I'm MEE6 the Discord Bot!",
        "command.directResponse": "Send private response",
        "command.description.heading": "Command Description",
        "command.edit.button": "EDIT",
        "command.edit.command": "Edit !{command}",
        "command.edit.heading": "Edit !{command} command",
        "command.ephemeral": "Delete command usage",
        "command.name.heading": "Command Name",
        "command.or": "or",
        "command.silent": "Do not reply to command",
        "command.toggle.private": "Private",
        "command.toggle.random": "Random",
        "command.toggle.inEmbed": "Embed",
        "confirmation.changes.detected": "Changes detected! Please save or cancel.",
        "confirmation.changes.save": "Save Changes",
        "cron.every": "Every",
        "cron.on": "On",
        "cron.mondays": "Mondays",
        "cron.tuesdays": "Tuesdays",
        "cron.wednesdays": "Wednesdays",
        "cron.thursdays": "Thursdays",
        "cron.fridays": "Fridays",
        "cron.saturdays": "Saturdays",
        "cron.sundays": "Sundays",
        "component.EmbedField.color.title": "Embed Color",
        "component.EmbedField.authorImage.placeholder": "Author image",
        "component.EmbedField.authorUrl.placeholder": "Author url",
        "component.EmbedField.authorName.placeholder": "Author name",
        "component.EmbedField.titleUrl.placeholder": "Title url",
        "component.EmbedField.title.placeholder": "Title text",
        "component.EmbedField.description.placeholder": "Content text",
        "component.EmbedField.thumbnail.placeholder": "Thumbnail",
        "component.EmbedField.image.placeholder": "Image",
        "component.EmbedField.footerIcon.placeholder": "Footer image",
        "component.EmbedField.footerText.placeholder": "Footer text",
        "component.EmbedField.error.author.url": "Embed author URL is invalid",
        "component.EmbedField.error.url": "Embed URL is invalid",
        "component.EmbedField.errorUrl": "URL is invalid",
        "component.EmbedField.fields.title": "Fields",
        "component.EmbedField.fields.delete": "Delete field",
        "component.EmbedField.fields.inline": "Inline",
        "component.EmbedField.fields.inline.tooltip.true": "This field is inline",
        "component.EmbedField.fields.inline.tooltip.false": "This field is not inline and takes all the embed width",
        "component.EmbedField.fields.name": "Field name",
        "component.EmbedField.fields.value": "Field value",
        "component.ImageViewer.placeholder": "Add an image",
        "component.ImageViewer.remove": "Remove image",
        "component.LocaleDropdownMenu.noLocale.placeholder": "None",
        "component.RestrictedChannels.header.channel": "Channel",
        "component.RestrictedChannels.header.command_channels": "Commands",
        "component.RestrictedChannels.header.image_channels": "Images",
        "component.RestrictedChannels.header.video_channels": "Videos",
        "duration.day": "{count, plural, =0 {days} one {day} other {days}}",
        "duration.minute": "{count, plural, =0 {minutes} one {minute} other {minutes}}",
        "duration.hour": "{count, plural, =0 {hours} one {hour} other {hours}}",
        "error.back": "Go back to MEE6 land!",
        "error.modal.title": "Oops, an error occured!",
        "error.modal.close": "Close",
        "error.chargebee": "Failed to load billing data. Please clear your cache and refresh the page to try again.",
        "error.gateway.reconnection": "Failed to retrieve server data for the guild #{guildID}",
        "exceptions.post.message.missing.permissions": "The bot cannot post in this channel. Please fix the bot's permissions!",
        "exceptions.add.reaction.missing.permissions": "The bot cannot add reactions. Please fix the bot's permissions!",
        "exceptions.vanity.url.taken": "Vanity URL is already taken, please choose another one.",
        "exceptions.vanity.url.not.allowed": "Vanity URL is not allowed, please choose another one.",
        "exceptions.must.be.premium": "Server must be premium to do this.",
        "exceptions.not.premium": "Server is not premium",
        "exceptions.guild.billing.profile.not.found": "Server billing profile not found.",
        "exceptions.subscription.not.found": "No subscription found for that guild.",
        "exceptions.not.the.payer": "You are not the payer of that subscription!",
        "exceptions.max.number.of.transfer.reached": "You cannot transfer that subscription again! Please contact us at hi@mee6bot.com.",
        "exceptions.guild.channel.not.found": "Channel not found on your server!",
        "exceptions.missing.manage.webhook.permission": "The bot is missing the 'Manage Webhooks' permission!",
        "exceptions.bad.token": "Failed to authenticate with the provided token.",
        "exceptions.custom.bot.disabled": "Custom bot is not enabled for this guild.",
        "exceptions.bad.stream.url": "Invalid Stream URL. It should link to either https://twitch.tv/ or https://youtube.com/.",
        "exceptions.custom.bot.invalid.status": "Invalid status, have you filled all the fields?",
        "exceptions.not_a_text_channel": "This is not a text channel.",
        "exceptions.file_extension_not_allowed": "This file extension is not allowed!",
        "exceptions.missing_image_file": "The request is missing an image file!",
        "exceptions.guild_channel_not_found": "Server channel not found!",
        "exceptions.command_id_already_exists": "This custom command name already exists.",
        "exceptions.missing_scope": "The permissions you have given do not allow to perform this action. You must reconnect with your discord account and grant required permissions to continue",
        "exceptions.invalid_plan": "The plan or period you have selected is invalid",
        "exceptions.user_already_pro_subscriber": "You have MEE6 Pro already!",
        "exceptions.unknown_embed_message": "It seems that the embed message you are trying to update has been deleted! Please create a new embed.",
        "exceptions.webhook.max_reached": "Maximum number of webhooks reached for this channel. Remove unused webhooks and try again.",
        "exceptions.statistics.duplicate_counter": "The same counter already exists.",
        "exceptions.statistics.failed_creation": "Failed to create counter.",
        "exceptions.statistics.max_counters": "Maximum number of counters reached.",
        "exceptions.statistics.not_found": "Counter not found.",
        "fields.channel": "Channel",
        "fields.channelPost": "Post in channel",
        "fields.message": "Message",
        "fields.role": "Role",
        "fields.embed": "Embed",
        "fields.description": "Description",
        "footer.best": "MEE6 is the best Discord bot to bootstrap and grow your Discord server",
        "footer.copy": "Copyright © 2018 - 2021 Sidescroll Ventures SAS",
        "footer.nav.contact": "Contact",
        "footer.nav.help": "Help desk",
        "footer.nav.hiring": "We're hiring",
        "footer.nav.home": "Home",
        "footer.nav.leveling": "Leveling",
        "footer.nav.moderation": "Moderator",
        "footer.nav.music": "Music",
        "footer.nav.premium": "Premium",
        "footer.nav.support": "Support server",
        "footer.nav.terms": "Terms",
        "footer.nav.privacy": "Privacy Policy",
        "footer.ready": "Ready to build the best Discord server ?",
        "googleFontsSelect.placeholder": "Search for a font...",
        "guildLogo.alt": "Logo of {name}",
        "guildSelection.goToDashboard": "Go to Dashboard",
        "guildSelection.setupMEE6": "Set up MEE6",
        "guildSelection.setupCustomBot": "Set up a Custom Bot",
        "guildSelection.noServers": "Oops, looks like you don't have any servers. :(",
        "guildSelection.discordAccount": "Are you sure you're connected to the right Discord account?",
        "guildSelection.help": "Join our support server",
        "header.login": "Login",
        "header.moderation": "Moderation",
        "header.leveling": "Leveling",
        "header.music": "Music",
        "header.premium": "Premium",
        "header.upgrade": "Upgrade",
        "header.tutorials": "Tutorials",
        "header.support": "Support Server",
        "header.plugins": "Plugins",
        "header.leaderboard": "Leaderboard",
        "header.settings": "Settings",
        "header.dropdown.myServers": "My Servers",
        "header.dropdown.editRankCard": "Edit my personal rank card",
        "header.dropdown.billing": "Billing",
        "header.dropdown.language": "Language",
        "header.dropdown.logout": "Logout",
        "home.hero.button.alt": "MEE6",
        "home.hero.button.addToDiscord": "Add to Discord",
        "home.hero.button.seeFeatures": "See features",
        "home.hero.button.learnMore": "Learn more",
        "home.hero.title": "Build the best Discord Server!",
        "home.hero.description": "Configure moderation, leveling, Twitch alerts, and much more with the most easy-to-use dashboard!",
        "home.section.alerts.alt": "Twitch, Mixer, YouTube, Reddit, and Twitter Discord notifications",
        "home.section.alerts.title": "Easy to set up announcement plugins",
        "home.section.alerts.description.1": "Set up one of the various announcement plugins to notify your server when you or your favorite content creators begin to stream, upload, and post content. You can easily set up streaming alerts for Twitch and Mixer, upload alerts for YouTube, and post alerts for Reddit and Twitter.",
        "home.section.alerts.description.2": "Get your favorite content without ever leaving your Discord server!",
        "home.section.customCommands.alt": "Creating a custom command",
        "home.section.customCommands.title": "Easily Create Custom Commands",
        "home.section.customCommands.description": "The MEE6 Dashboard gives you full control to create the command of your dreams! Create commands that automatically give and remove roles and send messages in the current channel or in DM.",
        "home.section.levels.alt": "Discord server leveling leaderboard",
        "home.section.levels.title": "Levels and XP in your Discord Server",
        "home.section.levels.description.1": "Gamers love to grind. Use our leveling system to identify and reward the most active members of your community! Let them show off a cool customizable rank card and compete for the mighty first spot of your leaderboard!",
        "home.section.levels.description.2": "Automatically give roles when they reach a certain level to reward the most active members with access to exclusive channels and privileged permissions.",
        "home.section.moderation.alt": "Setting up moderation, auto-moderator",
        "home.section.moderation.title": "Highly customizable moderation to protect your server from trolls and goblins.",
        "home.section.moderation.description.1": "The internet can be a dangerous place. Protect your server from ads, links, swearing, excessive emojis, and much more thanks to our easy-to-use moderation system.",
        "home.section.moderation.description.2": "Set up automated actions to help you moderate your server depending on the number of infractions a user has committed, and fine-tune the actions with timers. No more manually muting, kicking, and unbanning people, let MEE6 do the job for you.",
        "home.section.welcomeMessage.alt": "Creating a welcome message",
        "home.section.welcomeMessage.title": "Welcome Message and Auto-Role",
        "home.section.welcomeMessage.description.1": "Take advantage of the welcome message to inform newcomers about your server rules, topic, or ongoing events. ",
        "home.section.welcomeMessage.description.2": "You can also give them roles right after they join or just simply give them a warm welcome!",
        "ingredients.commandArg.1.hint": "First command argument",
        "ingredients.commandArg.2.hint": "Second command argument",
        "ingredients.commandArg.3.hint": "Third command argument",
        "ingredients.random.hint": "Random number between 1 and 10",
        "ingredients.server.name.hint": "The name of your server",
        "ingredients.server.id.hint": "The id of your server",
        "ingredients.server.icon_url.hint": "A link to your server icon",
        "ingredients.server.icon.hint": "The icon hash of the server",
        "ingredients.server.owner.hint": "Mentions the server owner",
        "ingredients.server.owner_id.hint": "The id of the server owner",
        "ingredients.server.region.hint": "The region of your server",
        "ingredients.server.members_count.hint": "Total number of users",
        "ingredients.server.verification_level.hint": "The verificaiton of the server (from 0 to 4)",
        "ingredients.server.joined_at.hint": "Date the bot joined the server",
        "ingredients.user.hint": "Mentions the user",
        "ingredients.user.id.hint": "The id of the user",
        "ingredients.user.name.hint": "The name of the user",
        "ingredients.user.discriminator.hint": "The discriminator of the user (#1234)",
        "ingredients.user.idname.hint": "User in the form of @user#1234",
        "ingredients.user.avatar_url.hint": "A link to the user's avatar",
        "ingredients.user.avatar.hint": "The avatar hash of the user",
        "ingredients.user.bot.hint": "Whether the user is a bot",
        "ingredients.channel.hint": "Mentions the current channel",
        "ingredients.channel.name.hint": "Current channel name",
        "ingredients.channel.id.hint": "The id of the current channel",
        "ingredients.channel.type.hint": "The type of the current channel (from 0 to 4)",
        "ingredients.misc.random_ranged.hint": "Random number between x and y",
        "ingredients.misc.random.hint": "Random number between 0 and 10",
        "landing.leveling.metaTitle": "MEE6 - XP & Leveling Discord Bot",
        "landing.leveling.metaDescription": "Make your members earn XP points in your Leaderboard and automatically give them roles.",
        "landing.leveling.title": "The best leveling bot for Discord",
        "landing.leveling.subtitle": "Keep your members engaged and entertained with a top-notch leveling system. Reward them with XP points and keep track of the most active members on your customizable leaderboard.",
        "landing.leveling.bottomCta.title": "It's time to gamify your Discord server!",
        "landing.leveling.bottomCta.subtitle": "Set up the best leveling bot and boost the engagement in your server in less than 5 minutes!",
        "landing.leveling.block.xp.title": "Reward your members with XP points",
        "landing.leveling.block.xp.content": "When someone sends a message, MEE6 will give them XP points so they can level up. You can even tweak the difficulty by changing the amount of XP points earned per message.",
        "landing.leveling.block.rank.title": "Let your members compete for the best rank",
        "landing.leveling.block.rank.content": "All your members will have access to your server leaderboard and compete for the first rank! You can even customize your leaderboard banner and make it feel like home.",
        "landing.leveling.block.roles.title": "Reward your most active members with exclusive roles",
        "landing.leveling.block.roles.content": "Let MEE6 automatically give predefined roles to the members who reach a certain level. This allows you to give exclusive access to private channels or more permissions to your most active members.",
        "landing.leveling.block.rankCards.title": "Give your members cool rank cards",
        "landing.leveling.block.rankCards.content": "Each member will have a personal rank card and a server rank card they can brag with! They can either customize their personal card by changing its background and colors, or they can choose to show off your server card if you decide to create one.",
        "landing.moderation.metaTitle": "MEE6 - The most complete Discord Moderation Bot",
        "landing.moderation.metaDescription": "Set up powerful Auto-Moderation rules and Logging. Prevent bad words, spam, and raids in your server.",
        "landing.moderation.title": "The best moderation bot for Discord",
        "landing.moderation.subtitle": "Keep your server safe and clean thanks to a high-quality, customizable auto-moderator system!",
        "landing.moderation.bottomCta.title": "It's time to automate your Discord moderation!",
        "landing.moderation.bottomCta.subtitle": "Set up the best moderator bot in your Discord server in less than 5 minutes!",
        "landing.moderation.block.protection.title": "Prevent spammers from ruining your server",
        "landing.moderation.block.protection.content": "Protect your server from insults, bad links, excessive emojis, all-caps messages, and more with MEE6's auto-moderator system.",
        "landing.moderation.block.protection.images.swearing": "Bad words",
        "landing.moderation.block.protection.images.allCaps": "All-caps",
        "landing.moderation.block.protection.images.links": "Links",
        "landing.moderation.block.protection.images.invites": "Invites",
        "landing.moderation.block.protection.images.mentions": "Mentions",
        "landing.moderation.block.protection.images.zalgo": "Zalgo",
        "landing.moderation.block.protection.images.emojis": "Emojis",
        "landing.moderation.block.protection.images.repeatedText": "Repeated text",
        "landing.moderation.block.protection.images.spoiler": "Spoilers",
        "landing.moderation.block.audit.title": "Keep track of what's happening in your server",
        "landing.moderation.block.audit.content": "Choose a private channel where MEE6 will notify you and your moderators whenever someone gets kicked, banned, muted, and more!",
        "landing.moderation.block.rules.title": "Relieve your moderators from repetitive tasks",
        "landing.moderation.block.rules.content": "Define clear rules that MEE6 will follow whenever someone is committing too many infractions.",
        "landing.moderation.block.commands.title": "Moderator Commands",
        "landing.moderation.block.commands.content": "Give your moderators the right tools to keep your server clean through MEE6's commands.",
        "landing.moderation.block.commands.description.ban": "Bans a user from the server",
        "landing.moderation.block.commands.description.tempban": "Temporarily bans a user from the server",
        "landing.moderation.block.commands.description.clear": "Delete a channel's messages",
        "landing.moderation.block.commands.description.infractions": "Displays a user's infractions",
        "landing.moderation.block.commands.description.kick": "Kicks a user from the server",
        "landing.moderation.block.commands.description.mute": "Server-mutes a user",
        "landing.moderation.block.commands.description.tempmute": "Temporarily server-mutes a user",
        "landing.moderation.block.commands.description.role-info": "Get information about a particular role",
        "landing.moderation.block.commands.description.server-info": "Get information about the current server",
        "landing.moderation.block.commands.description.slowmode": "Enables or Disables slowmode in a channel",
        "landing.moderation.block.commands.description.unban": "Unbans a user from the server",
        "landing.moderation.block.commands.description.unmute": "Unmutes a user",
        "landing.moderation.block.commands.description.user-info": "Get information about a particular user",
        "landing.moderation.block.commands.description.warn": "Warns a user",
        "landing.music.metaTitle": "MEE6 - The Best Free Music Bot for Discord",
        "landing.music.metaDescription": "Listen to Music for free with your friends and record your conversations. Now with a visual music player!",
        "landing.music.title": "The best free music bot for Discord",
        "landing.music.subtitle": "Listen to music with your friends right from your Discord server with the most stable and intuitive music bot.",
        "landing.music.bottomCta.title": "It's time to add some music to your Discord server!",
        "landing.music.bottomCta.subtitle": "Set up the best music bot for Discord in less than 5 minutes!",
        "landing.music.block.player.title": "Visual player to control your music",
        "landing.music.block.player.content": "No more complicated commands to play your music and manage your playlist. Use our cool dashboard to directly search for songs, replay them, and play them in your Discord server.",
        "landing.music.block.features.title": "All the features you would expect and much more!",
        "landing.music.block.features.content": "24/7 playing times without interruptions, looping, volume boosting, seeking, and more... Your members can even vote to skip a song if they don't like it thanks to our revolutionary democratic system!",
        "landing.music.block.source.title": "Play your music from any source",
        "landing.music.block.source.content": "We support Soundcloud, YouTube, Twitch, and more!",
        "landing.music.block.blindtest.title": "Guess the song name and artist to earn points",
        "landing.music.block.blindtest.content": "Challenge your friends to a friendly music quiz. MEE6 will play short samples from different songs. Be the first to guess the song and artist before the time runs out to earn points!",
        "landing.music.block.commands.title": "Music Commands",
        "landing.music.block.commands.description.play": "Start playing from the queue",
        "landing.music.block.commands.description.search": "Search for a song",
        "landing.music.block.commands.description.record": "Record the current conversation in a voice channel",
        "landing.music.block.commands.description.seek": "Jump to a specific moment in the song",
        "landing.music.block.commands.description.volume": "Changes the volume of the song up to 200%",
        "landing.music.block.commands.description.add": "Add a song to the queue",
        "landing.music.block.commands.description.queue": "List the songs in the queue",
        "landing.music.block.commands.description.clear-queue": "Remove every song from the queue",
        "landing.music.block.commands.description.skip": "Skip to the next song in the queue",
        "landing.music.block.commands.description.vote-skip": "Starts a vote to skip to the next song in the queue",
        "landing.music.block.commands.description.join": "Make the bot join your voice channel",
        "landing.music.block.commands.description.leave": "Make the bot leave your voice channel",
        "landing.music.block.commands.description.stop": "Stop the current song",
        "landing.music.block.commands.description.start-quiz": "Start a music quiz with your friends",
        "landing.music.block.commands.description.stop-quiz": "Stops the current music quiz",
        "landing.music.block.commands.description.stop-recording": "Stop the recording and get the link to the audio file",
        "leaderboard.reset.button": "Reset XP",
        "leaderboard.banner": "Leaderboard Banner",
        "leaderboard.upload.banner.button": "Upload Banner",
        "leaderboard.upload.banner.button.uploading": "Uploading Banner...",
        "leaderboard.reset.modal.title": "Reset everybody's XP?",
        "leaderboard.reset.modal.warning": "This action is strictly irreversible! Everyone will lose their XP and Levels!!!",
        "leaderboard.removeBanner.modal.title": "Remove the current banner?",
        "leaderboard.removeBanner.modal.warning": "Are you sure you want to remove the current leaderboard banner?",
        "leaderboard.adminPanel.title": "Admin Actions",
        "leaderboard.player.reset.modal.warning": "You are about to reset {player}'s Levels and XP! This action is strictly irreversible!",
        "leaderboard.player.reset.modal.title": "Reset member's XP?",
        "leaderboard.getPremium": "Get Premium",
        "leaderboard.editRankCard.button": "Edit your personal {prefix}rank card",
        "leaderboard.role.rewards.block.title": "Role Rewards",
        "leaderboard.howItWorks.block.title": "How It Works",
        "leaderboard.howItWorks.description.xp": "Every minute that you're messaging, you randomly gain between {min} and {max} XP.",
        "leaderboard.howItWorks.description.flood": "To avoid spamming, earning XP is limited to once a minute per user.",
        "leaderboard.howItWorks.description.cmd": "In the server, you type {prefix}rank to see your rank and level.",
        "leaderboard.login.cta.text": "Edit your Personal Rank Card",
        "leaderboard.useDefaultRankCard": "Use server Rank Card",
        "leaderboard.placeholder.text": "Start sending messages in your server to get ranked!",
        "leaderboard.stats.level": "LEVEL",
        "leaderboard.stats.rank": "RANK",
        "leaderboard.stats.experience": "EXPERIENCE",
        "leaderboard.stats.messages": "MESSAGES",
        "leaderboard.invite.text": "Join Server",
        "leaderboard.invite.alreadyJoinedTooltip.text": "You are already part of this server",
        "leaderboard.invite.confirm.title": "Join server?",
        "leaderboard.invite.confirm.description": 'You are about to join "{guild}" Discord server.',
        "leaderboard.adminPanel.actions.uploadBanner": "Upload banner",
        "leaderboard.adminPanel.actions.removeBanner": "Remove current banner",
        "leaderboard.adminPanel.actions.resetAllXP": "Reset all XP",
        "leaderboard.adminPanel.actions.getPremium": "Upgrade to Premium",
        "leaderboard.adminPanel.actions.settings": "Settings",
        "leaderboard.removeAd": "Remove ad",
        "leaderboardSettings.title": "Leaderboard settings",
        "leaderboardSettings.see": "👀 See leaderboard",
        "leaderboardSettings.invite": "Allow users to join your server through the leaderboard",
        "leaderboardSettings.invite.description": "Displays a button to join your server from your leaderboard page.",
        "leaderboardSettings.invite.channel": "Invite to channel",
        "leaderboardSettings.public": "Make my server's leaderboard public",
        "leaderboardSettings.public.description": "Enabling this option will allow your leaderboard to be seen by anyone who has the link, or by searching your server on Google.",
        "leaderboardSettings.vanity": "Vanity URL",
        "leaderboardSettings.vanity.description": "Get a cool URL customized with your guild name to access your leaderboard.",
        "notFound.title": "Hey Major Tom, looks like you're on the wrong planet!",
        "moderator.auto.mod.heading": "Auto-Moderator",
        "moderator.auto.mod.text": "The Auto-Moderator is composed of the checks below. You can enable/disable them. You can also configure the actions that will be taken when those checks are triggered.",
        "moderator.automatedActions.infraction": "{count, plural, =0 {{count} infractions} one {{count} infraction} other {{count} infractions}}",
        "moderator.automatedActions.for": "for",
        "moderator.automatedActions.heading": "Automated Actions",
        "moderator.automatedActions.orMore": "or more in the last",
        "moderator.automatedActions.placeholder": "You don't have any Automated Actions, click the ADD button to add some.",
        "moderator.automatedActions.ban": "ban",
        "moderator.automatedActions.tempBan": "temp ban",
        "moderator.automatedActions.mute": " mute",
        "moderator.automatedActions.tempMute": "temp mute",
        "moderator.automatedActions.kick": "kick",
        "moderator.automatedActions.text": "These allow you to let automod mute, kick, ban, temp mute, or temp ban automatically.",
        "moderator.automatedActions.when": "when someone has",
        "moderator.ignore.bots": "Auto-Moderator ignores and doesn't affect other bots",
        "moderator.logs.heading": "Audit Logging",
        "moderator.logs.text": "You can set a channel and events that will be sent to that particular channel. Don't miss anything happening in your server when you are not around!",
        "moderator.logs.channel": "Logging Channel",
        "moderator.logs.ignored.channels": "Ignored channels",
        "moderator.logs.ignored.channels.description": "Messages updated and deleted in these channels will be ignored. This is useful if you have super-duper private channels that you don't want your moderators to know about.",
        "moderator.logs.ignoreBots": "Do not log actions made by bots",
        "moderator.logs.message_updated": "Message updated",
        "moderator.logs.message_deleted": "Message deleted",
        "moderator.logs.invite_posted": "Invite posted",
        "moderator.logs.nickname_changed": "Nickname changed",
        "moderator.logs.role_created": "Role created",
        "moderator.logs.role_updated": "Role updated",
        "moderator.logs.role_deleted": "Role deleted",
        "moderator.logs.channel_created": "Channel created",
        "moderator.logs.channel_deleted": "Channel deleted",
        "moderator.logs.channel_updated": "Channel updated",
        "moderator.logs.member_voice_channel_joined": "Member joined voice channel",
        "moderator.logs.member_voice_channel_left": "Member left voice channel",
        "moderator.logs.member_banned": "Member banned",
        "moderator.logs.member_roles_changed": "Member roles changed",
        "moderator.logs.member_joined": "Member joined server",
        "moderator.logs.member_left": "Member left server",
        "moderator.logs.member_muted": "Member muted",
        "moderator.logs.member_unmuted": "Member unmuted",
        "moderator.logs.moderation_member_banned": "Moderation ban",
        "moderator.logs.moderation_member_unbanned": "Moderation unban",
        "moderator.logs.member_unbanned": "Member unbanned",
        "moderator.logs.member_boosting": "New server boost",
        "moderator.logs.member_not_boosting": "Server boost removed",
        "moderator.logs.guild_info_updated": "Server edited",
        "moderator.logs.guild_emojis_update": "Emojis updated",
        "moderator.logs.user_updated": "User updated",
        "moderator.logs.titles.channelEvents": "Channel Events",
        "moderator.logs.titles.membersEvents": "Member Events",
        "moderator.logs.titles.messagesEvents": "Message Events",
        "moderator.logs.titles.moderationEvents": "Moderation Events",
        "moderator.logs.titles.rolesEvents": "Role Events",
        "moderator.logs.titles.serverEvents": "Server Events",
        "moderator.logs.titles.voiceEvents": "Voice Events",
        "moderator.moderatorRoles.heading": "Moderator Roles",
        "moderator.moderatorRoles.text": 'You can add moderator roles. Users with one of these roles are considered your server moderators and are not affected by Auto-Moderator, they are also immune to moderator commands.\nModerator roles do not allow the use of moderator commands, you must add your moderator role as an "allowed role" inside each command by clicking on the command name.',
        "moderator.unban": "Unban",
        "moderator.unban.user": "Unban user?",
        "moderator.unban.confirmation": "User unbanned",
        "moderator.unban.none": "This user is not banned",
        "moderator.unmute.confirmation": "User unmuted",
        "moderator.unmute.user": "Unmute user?",
        "moderator.unmute.none": "This user is not muted",
        "moderator.infractions.deleted": "{count, plural, one {Infraction deleted} other {Infractions deleted}}",
        "moderator.infractions.delete": "{count, plural, one {Delete this infraction?} other {Delete all infractions?}}",
        "moderator.infractions.delete.button": "{count, plural, one {Delete this infraction} other {Delete {count} infractions}}",
        "moderator.infractions.none": "This user has no infractions",
        "plugins.commands": "Commands",
        "plugins.disable.button": "Disable",
        "plugins.enable.modal.title": "Enable the plugin?",
        "plugins.blindtest.name": "Music Quiz",
        "plugins.blindtest.description": "Guess the name of the artist and song to gain points",
        "plugins.blindtest.command.start-quiz.description": "Starts a Music Quiz",
        "plugins.blindtest.command.stop-quiz.description": "Stops the current Music Quiz",
        "plugins.commands.name": "Custom Commands",
        "plugins.commands.description": "Add awesome custom commands to your server",
        "plugins.commands.create": "Create a Command",
        "plugins.commands.type.textCommand": "Text Command",
        "plugins.commands.type.textCommand.description": "A simple command that responds with a custom message in DM or public channel",
        "plugins.commands.type.autoRole": "Auto-Role",
        "plugins.commands.type.autoRole.description": "A command that lets your members automatically give themselves one or multiple roles",
        "plugins.commands.type.advanced": "Advanced",
        "plugins.commands.type.advanced.description": "For complex commands that give/remove roles, send one or multiple messages at once, and more",
        "plugins.commands.premiumUnlock.advanced.title": "Unlock Auto-Role and Advanced commands",
        "plugins.commands.premiumUnlock.advanced.subtitle": "With MEE6 premium you can take your commands to a whole new level!",
        "plugins.commands.premiumUnlock.limit.title": "Upgrade your commands limit!",
        "plugins.commands.premiumUnlock.limit.subtitle": "Add up to 500 custom commands with MEE6 Premium!",
        "plugins.help.name": "Help",
        "plugins.help.description": "Enables the {prefix}help command for your server",
        "plugins.help.command.help.description": "Get a list of all available commands",
        "plugins.help.command.dashboard.description": "Get a nice link to your server dashboard",
        "plugins.levels.levelI": "Level {i}",
        "plugins.levels.name": "Levels",
        "plugins.levels.description": "Let your users gain XP and levels by participating in the chat!",
        "plugins.levels.command.levels.description": "Get a direct link to your servers leaderboard",
        "plugins.levels.command.rank.description": "Get your rank or another users rank",
        "plugins.levels.command.give-xp.description": "Give XP to anyone in the server",
        "plugins.levels.command.remove-xp.description": "Take XP away from anyone in the server",
        "plugins.levels.guild.currentRankCard.title": "Your current Server Rank Card",
        "plugins.levels.guild.defaultRankCard.title": "Default Server Rank Card",
        "plugins.levels.guild.rankCard.text": "You can customize the default {prefix}rank card in your server. By default, every member of your server will have that rank card.",
        "plugins.levels.guild.rankCard.edit": "Edit Server Rank Card",
        "plugins.levels.levelUp.heading": "Leveling Up",
        "plugins.levels.levelUp.announcement": "Level Up Announcement",
        "plugins.levels.levelUp.announcement.disabled": "Disabled",
        "plugins.levels.levelUp.announcement.currentChan": "Current Channel",
        "plugins.levels.levelUp.announcement.private": "Private Message",
        "plugins.levels.levelUp.announcement.custom": "Custom Channel",
        "plugins.levels.levelUp.announcement.channel": "Announcement Channel",
        "plugins.levels.levelUp.announcement.message": "Level Up Announcement Message",
        "plugins.levels.levelUp.text": "Whenever the user gains a level, MEE6 can send a personalized message.",
        "plugins.levels.noXp.roles": "No-XP Roles",
        "plugins.levels.noXp.roles.text": "You can set roles here that will stop users from gaining XP.",
        "plugins.levels.noXp.channels": "No-XP Channels",
        "plugins.levels.noXp.channels.text": "You can also prevent your members from gaining XP if they send messages in certain text channels.",
        "plugins.levels.roleRewards.heading": "Role Rewards Configuration",
        "plugins.levels.roleRewards.list.heading": "Role Rewards",
        "plugins.levels.roleRewards.placeholder": "You don't have any role rewards currently.",
        "plugins.levels.roleRewards.text": "Role rewards are roles that will be automatically given to a player when reaching a specific level. You can choose to stack them or to only keep the highest role reward.",
        "plugins.levels.roleRewards.type": "Role Rewards Type",
        "plugins.levels.roleRewards.type.0.name": "Stack previous rewards",
        "plugins.levels.roleRewards.type.0.description": "Users can have multiple rewards at once",
        "plugins.levels.roleRewards.type.1.name": "Remove previous rewards",
        "plugins.levels.roleRewards.type.1.description": "Users will only have the highest role reward",
        "plugins.levels.roleRewards.behavior.title": "Role rewards behavior",
        "plugins.levels.roleRewards.removeOnXpDrop.label": "Remove role reward when player is demoted",
        "plugins.levels.xp.rate.title": "XP Rate",
        "plugins.levels.xp.rate.description": "Change the leveling difficulty by tweaking the rate at which your members will gain XP.",
        "plugins.levels.xp.pro.disable": "Do not give extra XP to MEE6 Pro subscribers",
        "plugins.moderator.name": "Moderator",
        "plugins.moderator.description": "Power up your moderation with cool commands and automations!",
        "plugins.moderator.command.unban.description": "Unbans a user from the server",
        "plugins.moderator.command.ban.description": "Bans a user from the server",
        "plugins.moderator.command.tempban.description": "Temporarily bans a user from the server",
        "plugins.moderator.command.mute.description": "Server-mutes a user",
        "plugins.moderator.command.unmute.description": "Unmutes a user",
        "plugins.moderator.command.tempmute.description": "Temporarily server-mutes a user",
        "plugins.moderator.command.kick.description": "Kicks a user from the server",
        "plugins.moderator.command.warn.description": "Warns a user",
        "plugins.moderator.command.infractions.description": "Displays a user's infractions",
        "plugins.moderator.command.clear-all-infractions.description": "Remove all infractions of every user in the server",
        "plugins.moderator.command.slowmode.description": "Enables or Disables slowmode in a channel",
        "plugins.moderator.command.clear.description": "Delete a channel's messages",
        "plugins.moderator.command.user-info.description": "Get information about a particular user",
        "plugins.moderator.command.role-info.description": "Get information about a particular role",
        "plugins.moderator.command.server-info.description": "Get information about the current server",
        "plugins.moderator.managedChannels": "Restricted channels",
        "plugins.moderator.managedChannels.commands": "Commands-only channels",
        "plugins.moderator.managedChannels.images": "Image-only channels",
        "plugins.moderator.managedChannels.description": "Set-up image-only, video-only or commands-only channels. MEE6 will automatically delete all messages that are not images or commands in those channels.",
        "plugins.moderator.managedChannels.authorMessage": "Send a message to the author on message deletion",
        "plugins.moderator.managedChannels.replyMessage": "Reply in the channel on message deletion",
        "plugins.music.name": "Music",
        "plugins.music.description": "Listen to music directly on Discord",
        "plugins.music.controller": "Music Controller",
        "plugins.music.controller.description": "You can control the music plugin right from here. Make the bot join a particular voice channel, add a track, remove a track, and even re-order the tracks.",
        "plugins.music.controller.loop.text": "LOOP",
        "plugins.music.controller.loop.tooltip": "Loop the whole queue",
        "plugins.music.controller.247.text": "24 / 7 Mode",
        "plugins.music.controller.247.tooltip": "Make MEE6 stay in the voice channel 24/7",
        "plugins.music.controller.nowPlaying": "Now Playing",
        "plugins.music.controller.voiceChannel": "Voice Channel",
        "plugins.music.queue": "Music Queue",
        "plugins.music.remove": "REMOVE",
        "plugins.music.command.add.description": "Add a song to the queue",
        "plugins.music.command.add-playlist.description": "Add a YouTube playlist to the queue",
        "plugins.music.command.join.description": "Make the bot join your voice channel",
        "plugins.music.command.leave.description": "Make the bot leave your voice channel",
        "plugins.music.command.play.description": "Start playing from the queue",
        "plugins.music.command.next.description": "Skip current song",
        "plugins.music.command.queue.description": "List the songs in the queue",
        "plugins.music.command.search.description": "Search for a song",
        "plugins.music.command.skip.description": "Skip to the next song",
        "plugins.music.command.vote-skip.description": "Starts a vote to skip to the next song",
        "plugins.music.command.stop.description": "Stop the current song",
        "plugins.music.command.clear-queue.description": "Remove every song from the queue",
        "plugins.music.command.pause.description": "Pause the current playing song",
        "plugins.music.command.seek.description": "Change the current track's position",
        "plugins.music.command.resume.description": "Resume playing the current song",
        "plugins.music.command.volume.description": "Change the volume of the player",
        "plugins.music.command.np.description": "Display the current playing track",
        "plugins.music.command.replay.description": "Replay the current track",
        "plugins.music.command.previous.description": "Play the previous track",
        "plugins.music.search.placeholder": "Add a track to the queue...",
        "plugins.record.name": "Record",
        "plugins.record.description": "Record your voice as a nice mp3 file that you can save",
        "plugins.record.command.join.description": "Make the bot join your voice channel",
        "plugins.record.command.leave.description": "Make the bot leave your voice channel",
        "plugins.record.command.record.description": "Start a recording",
        "plugins.record.command.stop-recording.description": "Stop the current recording",
        "plugins.reddit.name": "Reddit",
        "plugins.reddit.description": "Get your favorite subreddits posted directly to your server",
        "plugins.search.name": "Search Anything",
        "plugins.search.description": "Search the internet for whatever you want!",
        "plugins.search.command.anime.description": "Search for anime on Kitsu",
        "plugins.search.command.manga.description": "Search for manga on Kitsu",
        "plugins.search.command.imgur.description": "Search for memes on Imgur",
        "plugins.search.command.youtube.description": "Search for videos on YouTube",
        "plugins.search.command.pokemon.description": "Search for Pokémon on the Pokéapi Pokédex",
        "plugins.search.command.twitch.description": "Search for any streamer on Twitch",
        "plugins.search.command.urban.description": "Search for slang definitions on Urban Dictionary",
        "plugins.twitch.name": "Twitch",
        "plugins.twitch.description": "Notify people when your favorite Twitch streamers go live",
        "plugins.twitch.followersCount": "{count, plural, =0 {no followers} one {1 follower} other {{count, number} followers}}",
        "plugins.twitch.defaultAnnouncementMessage": "Hey @everyone, '{streamer}', is now live on '{link}' ! Go check it out!",
        "plugins.twitch.searchChannelPlaceholder": "Search for a Twitch channel...",
        "plugins.twitch.new1": "Add a streamer",
        "plugins.twitch.new2": "Add more streamers",
        "plugins.twitch.longDescription": "You can add Twitch streamers here. Every time one of them starts streaming, MEE6 will automatically send a message to a pre-configured channel in your server.",
        "plugins.twitch.placeholder": 'You are not following any streamers, click "Add a streamer" to add one.',
        "plugins.twitch.bannedUser": "Banned user",
        "plugins.twitch.addMore": "Add more Twitch channels",
        "plugins.twitch.premium1": "With MEE6 Premium, you can add more than one Twitch channel to follow all your favorite streamers.",
        "plugins.twitch.premium2": "You'll also get awesome perks such as role rewards, advanced logging, and much more!",
        "plugins.twitch.yourChannel": "{count, plural, =0 {Your Twitch channel} one {Your Twitch channel} other {Your Twitch channels}}",
        "plugins.twitch.follow": "Receive a Discord notification when someone follows the channel",
        "plugins.twitch.defaultFollowMessage": "'{follower}' started following **'{streamer}'**!",
        "plugins.twitch.twitch.liveAutoRoleTitle": "Live streaming auto-role",
        "plugins.twitch.twitch.liveAutoRoleDescription": "You can give more visibility to your members whenever they are streaming. As soon as they start streaming, MEE6 will give them a special hoisted role.",
        "plugins.twitch.liveRoles": "Live Roles",
        "plugins.twitch.liveRolesDescription": "This is the list of roles that the bot will give to your members just after they start streaming on Twitch.",
        "plugins.twitch.liveRolesCheck": "Restrictions",
        "plugins.twitch.liveRolesCheckDisabled": "No restriction",
        "plugins.twitch.liveRolesCheckByRole": "Restrict by role",
        "plugins.twitch.allowedLiveRoles": "Allowed roles",
        "plugins.twitch.enableLiveRoles": "Give a special role to members streaming right now",
        "plugins.welcome.name": "Welcome",
        "plugins.welcome.description": "Give new users a warm welcome!",
        "plugins.youtube.name": "YouTube",
        "plugins.youtube.description": "Get notified when your favorite YouTubers post a video",
        "plugins.youtube.subscriberCount": "{count} subscribers",
        "plugins.youtube.searchChannelPlaceholder": "Search for a YouTube channel...",
        "plugins.youtube.defaultAnnouncementMessage": "Hey @everyone, **'{youtube_channel}'** just posted a video! Go check it out!",
        "plugins.youtube.longDescription": "You can add YouTube channels here. Every time one of them uploads a video, MEE6 will automatically send a message to a pre-configured channel in your server.",
        "plugins.youtube.new1": "Add a channel",
        "plugins.youtube.new2": "Add more channels",
        "plugins.youtube.yourChannel": "{count, plural, =0 {Your Youtube channel} one {Your Youtube channel} other {Your Youtube channels}}",
        "plugins.youtube.addMore": "Add more Youtube channels",
        "plugins.youtube.premium1": "With MEE6 Premium, you can add more than one YouTube channel to follow all your favorite creators.",
        "plugins.youtube.premium2": "You'll also get awesome perks such as role rewards, advanced logging, and much more!",
        "plugins.reddit.premium1": "With MEE6 Premium you can add more than one subreddit and never miss a post.",
        "plugins.reddit.premium2": "You'll also get awesome perks such as role rewards, advanced logging, and much more!",
        "plugins.reddit.addMore": "Add more subreddits",
        "plugins.reddit.new1": "Add a subreddit",
        "plugins.reddit.longDescription": "You can add subreddits to follow here. All the posts from these subreddits will be directly sent to a channel you specify.",
        "plugins.reddit.yourChannel": "{count, plural, =0 {Your subreddit} one {Your subreddit} other {Your subreddits}}",
        "plugins.reddit.embeds.wide": "Wide embeds",
        "plugins.reddit.embeds.compact": "Compact embeds",
        "plugins.reaction_roles.name": "Reaction Roles",
        "plugins.reaction_roles.longDescription": "Let your members get roles by reacting to a message",
        "plugins.guild_embeds.name": "Embeds",
        "plugins.guild_embeds.description": "Send and manage rich embed messages",
        "plugins.reaction_roles.description": "Let your members get roles by reacting to a message",
        "plugins.reaction_roles.default.text": "Default",
        "plugins.reaction_roles.default.description": "Reaction roles messages are special messages that let your members automatically pick up roles when they react to a particular message. It is especially useful when making a verification system for your Discord server.",
        "plugins.reaction_roles.reverse.text": "Reverse",
        "plugins.reaction_roles.reverse.description": "Remove roles when you click on a reaction, give them back when you remove your reaction",
        "plugins.reaction_roles.reactions": "Reactions and roles",
        "plugins.reaction_roles.multipleRolesText": "Allow members to pick up multiple roles",
        "plugins.reaction_roles.new": "New Message",
        "plugins.reaction_roles.addNewReaction": "Add reaction",
        "plugins.reaction_roles.mode": "Reaction Mode",
        "plugins.reaction_roles.inEmbed": "Embed",
        "plugins.reaction_roles.embedColor": "Embed Color",
        "plugins.reaction_roles.placeholder": "You don't have any reactions yet. Click on the Add Reaction button to add one.",
        "plugins.reaction_roles.invalid": "Invalid reaction message, please check MEE6 can read in all channels.",
        "plugins.reaction_roles.availableSlots": " — {count} {count, plural, one {slot} other {slots}} available",
        "plugins.reaction_roles.addMore": "Add more messages",
        "plugins.reaction_roles.premium1": "With MEE6 Premium, you can add more than one Reaction Roles message and up to 20 reactions per message.",
        "plugins.reaction_roles.premium2": "You'll also get awesome perks such as role rewards, advanced logging, and much more!",
        "plugins.reaction_roles.yourMessage": "{count, plural, =0 {Your Message} one {Your Message} other {Your Messages}}",
        "plugins.reaction_roles.premiumUnlock.title": "Upgrade your reactions limits!",
        "plugins.reaction_roles.premiumUnlock.subtitle": "Unlock MEE6 Premium to get up to 20 reactions per message.",
        "plugins.reaction_roles.messageWarning": "Could not load the message! Either the bot is missing read and read history permissions or the message has been deleted!",
        "plugins.timers.name": "Timers",
        "plugins.timers.description": "Send custom messages on repeat every few minutes/hours",
        "plugins.timers.add": "Add Timer",
        "plugins.timers.defaultMessage": "Hey, I'm a timer!",
        "plugins.timers.longDescription": "Timers are messages sent every x time in a specific channel. They're useful when you want to give reminders for example.",
        "plugins.timers.editModalTitle": "Edit Timer",
        "plugins.timers.intervalField": "Interval",
        "plugins.timers.placeholder": 'You don\'t have any timers right now. Click on the "{addTimerButton}" button to add one.',
        "plugins.timers.inEmbed": "Embed",
        "plugins.timers.delete": "Delete this timer",
        "plugins.welcome.welcomeCard": "Send a welcome card when a user joins the server",
        "plugins.welcome.enablePublicWelcome": "Send a message when a user joins the server",
        "plugins.welcome.publicWelcomeChannel": "Welcome Message Channel",
        "plugins.welcome.publicWelcomeMessage": "Welcome Message",
        "plugins.welcome.enablePrivateWelcome": "Send a private message to new users",
        "plugins.welcome.privateWelcomeMessage": "Private Message",
        "plugins.welcome.enableGoodbye": "Send a message when a user leaves the server",
        "plugins.welcome.goodbyeChannel": "Goodbye Message Channel",
        "plugins.welcome.goodbyeMessage": "Goodbye Message",
        "plugins.welcome.welcomeRoles": "Roles to give",
        "plugins.welcome.enableRoles": "Give a role to new users",
        "plugins.welcome.customizeWelcomeCard": "Customize your welcome card",
        "plugins.welcome.welcomeCardPreview": "Welcome card preview",
        "plugins.welcome.welcomeCardTitle": "Title",
        "plugins.welcome.welcomeCardSubtitle": "Subtitle",
        "plugins.welcome.welcomeCardFont": "Font",
        "plugins.welcome.welcomeCardFrontColor": "Text color",
        "plugins.welcome.welcomeCardBackgroundColor": "Background color",
        "plugins.welcome.welcomeCardOpacity": "Overlay opacity",
        "plugins.welcome.welcomeCardBackground": "Background",
        "plugins.welcome.inEmbed": "Embed",
        "plugins.welcome.welcomeRoles.delayNotPending": "Delay at server rules acceptance",
        "plugins.welcome.enableRoles.rulesAndDelay": "Roles are given to users when they accept the server rules",
        "plugins.welcome.enableRoles.rulesAndNoDelay": "There is a conflict with your server configuration,\n giving a role to new users when they join will bypass the Rules Screening on this Discord Server (enabled in Server Settings > Community Settings). \n Please consider enabling the delay option below.",
        "plugins.welcome.enableRoles.noRulesAndDelay": "Please note that delaying at server rules acceptance will have no effect since you don't use the Discord Rules Screening (can be enabled in server settings > community settings)",
        "plugins.welcome.enableRoles.noRulesAndNoDelay": "Roles are given to new users when they join the server",
        "plugins.twitter.name": "Twitter",
        "plugins.twitter.description": "Get notified when your favorite Twitter accounts post a tweet",
        "plugins.twitter.searchChannelPlaceholder": "Search for a Twitter user...",
        "plugins.twitter.defaultAnnouncementMessage": "Hey @everyone, **{twitter_user}** just posted a new Tweet!",
        "plugins.twitter.longDescription": "You can subscribe to Twitter accounts here. Every time one of them posts a tweet, MEE6 will automatically send it to a pre-configured channel in your server.",
        "plugins.twitter.new1": "Add subscription",
        "plugins.twitter.new2": "Add more subscriptions",
        "plugins.twitter.yourChannel": "{count, plural, one {Your Twitter Subscription} other {Your Twitter Subscriptions}}",
        "plugins.twitter.addMore": "Add more Twitter subscriptions",
        "plugins.twitter.premium1": "With MEE6 Premium, you can have more than one Twitter subscription so that you never miss a Tweet from people you follow.",
        "plugins.twitter.premium2": "You'll also get awesome perks such as role rewards, advanced logging, and much more!",
        "plugins.twitter.getStarted": "Get started",
        "plugins.twitter.getStartedDescription": "You will need to connect your account first. After that, you'll be able to subscribe to any Twitter account tweets.",
        "plugins.twitter.connect": "Connect your Twitter account",
        "plugins.customCommands.availableSlots": " — {count} {count, plural, one {slot} other {slots}} available",
        "plugins.customCommands.placeholder": "You have no custom commands yet.",
        "plugins.customCommands.delete": "Delete this custom command",
        "premium.plan.title": "{months, plural, =12 {1-year plan} =24 {2-year plan} =36 {3-year plan} other {{months}-month plan}}",
        "premium.plan.current": "Current plan",
        "premium.plan.active": "Active",
        "premium.plan.unavailable": "Unavailable",
        "premium.plan.lifetime": "Lifetime plan",
        "premium.plan.footnote": "billed every {months, plural, =1 {month} =12 {year} =24 {2 years} =36 {3 years} other {{months} months}}",
        "premium.plan.lifetimeFootnote": "paid only once",
        "premium.plan.tooltipLifetime": "Buying a lifetime subscription is cheaper if you already own one!",
        "premium.plan.select": "Get {months, plural, =12 {1-Year Plan} =24 {2-Year Plan} =36 {3-Year Plan} other {{months}-Month Plan}}",
        "premium.plan.upgrade": "Upgrade to {months, plural, =12 {1-Year Plan} =24 {2-Year Plan} =36 {3-Year Plan} other {{months}-Month Plan}}",
        "premium.plan.downgrade": "Downgrade to {months, plural, =12 {1-Year Plan} =24 {2-Year Plan} =36 {3-Year Plan} other {{months}-Month Plan}}",
        "premium.plan.freeUpgrade": "Upgrade for free ({count} remaining)",
        "premium.plan.lifetimeSelect": "Get Lifetime Plan",
        "premium.plan.lifetimeUpgrade": "Upgrade to Lifetime",
        "premium.plan.save": "Save {discount}%",
        "premium.plan.contactSupport": "Contact support to change plan",
        "premium.plans.show": "View Plans (Upgrade or Downgrade)",
        "premium.plans.hide": "Hide Plans",
        "premium.plans.bestValue": "Best value",
        "premium.plans.mostPopular": "Most popular",
        "premium.plans.servers": "{count, plural, =1 {1 server} other {{count} servers}}",
        "premium.plans.perMonth": "per month",
        "premium.plans.oneshot": "single payment",
        "premium.plans.tip1": "FYI: The lifetime plan includes the biggest savings and is fully refundable for 7 days.",
        "premium.plans.tip2": "You can transfer it at any time to another Discord server.",
        "premium.plans.feature1": "Unlock all features of the bot and remove restrictions",
        "premium.plans.feature2": "Transferable to your other Discord servers",
        "premium.plans.feature3": "7-day money back guarantee",
        "premium.customBot.title": "Also recommended for the best experience",
        "premium.customBot.recommended": "Recommended",
        "premium.customBot.description": "Customize MEE6 with your own avatar and name. We run your own copy of MEE6 on our servers.",
        "premium.customBot.add": "Add",
        "premium.customBot.added": "Added",
        "premium.customBot.perMonth": "/mo",
        "premium.customBot.singlePayment": "(single payment)",
        "premium.customBot.included": "(included)",
        "premium.button.iWantIt": "I want it",
        "premium.button.noThanks": "No thanks",
        "premium.button.preview": "Click to preview",
        "premium.how": "How it works",
        "premium.flash.serverStatus": "Server status",
        "premium.flash.restricted": "Restricted",
        "premium.flash.unlock": "Unlock all features now",
        "premium.header.title": "MEE6 PREMIUM",
        "premium.header.tagline": "Take Your Server To The Next Level",
        "premium.offer.dontmiss": "Don't miss out!",
        "premium.offer.sale": "New year sale ends soon! Up to 65% off deals for a limited time.",
        "premium.description": "Support MEE6's development and unlock the full potential of your server!",
        "premium.comparison.title": "Plans comparison",
        "premium.comparison.free": "Free",
        "premium.comparison.premium": "Premium",
        "premium.comparison.welcome": "Welcome/goodbye messages",
        "premium.comparison.autoRole": "Automatic role for new users",
        "premium.comparison.welcomeImage": "Welcome images",
        "premium.comparison.customCommands": "Custom commands",
        "premium.comparison.customCommandsNumber": "Number of custom commands",
        "premium.comparison.advancedCustomCommands": "Advanced custom commands (give/remove role)",
        "premium.comparison.embedMessages": "Embed messages with editor",
        "premium.comparison.numberOfEmbeds": "Number of embed messages",
        "premium.comparison.searchCommand": "Search command",
        "premium.comparison.auditLogging": "Audit logging",
        "premium.comparison.auditLogging.free": "Some events",
        "premium.comparison.auditLogging.premium": "All events",
        "premium.comparison.basicAutoMod": "Basic automatic moderation",
        "premium.comparison.advancedAutoMod": "Advanced automatic moderation (server invites, external links)",
        "premium.comparison.configurableAutoMod": "Configurable automated actions",
        "premium.comparison.restrictedChannels": "Restricted channels (image-only, command-only, ...)",
        "premium.comparison.timedMessages": "Timed messages",
        "premium.comparison.reactionRoleMessages": "Reaction role messages",
        "premium.comparison.reactionRoleMessagesNumber": "Number of reaction role messages",
        "premium.comparison.reactionRoleMessagesMaxRole": "Maximum number of reaction on each reaction role message",
        "premium.comparison.levelsPlugin": "Levels plugin",
        "premium.comparison.roleRewards": "Role rewards based on XP",
        "premium.comparison.adjustableXPRate": "Adjustable XP rate",
        "premium.comparison.giveRemoveXP": "Give/remove XP commands",
        "premium.comparison.twitchNotifications": "Twitch notifications",
        "premium.comparison.youtubeNotifications": "YouTube notifications",
        "premium.comparison.twitterNotifications": "Twitter notifications",
        "premium.comparison.redditNotifications": "Reddit notifications",
        "premium.comparison.musicQuiz": "Music quiz",
        "premium.comparison.musicQuiz.free": "3 games per day",
        "premium.comparison.musicQuiz.premium": "Unlimited",
        "premium.comparison.record": "Recording",
        "premium.comparison.record.free": "2 minutes max",
        "premium.comparison.record.premium": "Up to 6 hours",
        "premium.comparison.maxMusicQueue": "Max music queue size",
        "premium.comparison.maxMusicQueue.free": "50 tracks",
        "premium.comparison.maxMusicQueue.premium": "1000 tracks",
        "premium.comparison.customPrefix": "Custom prefix",
        "premium.comparison.vanityURL": "Leaderboard vanity URL",
        "premium.comparison.joinButton": "Leaderboard join button",
        "premium.faq.currency.title": "Can I pay in another currency?",
        "premium.faq.currency.text": "The only currency available is the one displayed. However, you can still pay in your own currency because most payment processors will do the conversion for you for a minor fee (usually a few cents). PayPal does not take fees for conversion.",
        "premium.faq.guilds.title": "How many Discord servers is my subscription valid for?",
        "premium.faq.guilds.text": "A subscription is valid for a single Discord server. If you wish to get premium for multiple servers, you need a subscription for each server. But we do offer bundle discounts on the lifetime plan.",
        "premium.faq.invoice.title": "Can I get an invoice for my payment?",
        "premium.faq.invoice.text": 'Yes! After subscribing you can see and download all your invoices in your "Billing" tab (located in the dropdown of your profile, in the top right of the page). They should be valid for almost all purposes, including business accounting. If you need any help with an invoice, please contact us.',
        "premium.faq.money.title": "What is the money used for?",
        "premium.faq.money.text": "MEE6 is a real company run by real people. Premium is what keeps it alive. We use the money to pay salaries to our developers and to cover hosting costs and taxes.",
        "premium.faq.payment.title": "What payment methods are supported?",
        "premium.faq.payment.text": "Currently, we support only credit cards, debit cards, and PayPal. Please note that if your PayPal account is not verified, the transaction might not work. You can contact us if you would like to pay with another payment method.",
        "premium.faq.premium.title": "What is MEE6 Premium?",
        "premium.faq.premium.text": "MEE6 Premium is a subscription you can get to support the development of the bot. It is not mandatory to use MEE6 but allows you to unlock exclusive features if you get it.",
        "premium.faq.refund.title": "Can I get a refund if I don't like it?",
        "premium.faq.refund.text": "We want everyone to have a great experience with MEE6 Premium. If you're not satisfied during your first week, please contact us and we will issue you a full refund.",
        "premium.faq.secure.title": "Is my payment secure?",
        "premium.faq.secure.text": "Yes. We never have access to your debit/credit card information. Payments are handled through Stripe, a payment processor trusted by millions of companies worldwide and protected with state-of-the-art technologies. We also never have access to your PayPal account info and your transactions are protected by PayPal's Purchase Protection for Buyers.",
        "premium.faq.stop.title": "Can I stop my subscription anytime?",
        "premium.faq.stop.text": "Yes. You can stop your subscription at any time by going to your billing tab. Your subscription will still be valid until the end of the period you have paid for, but you will not be charged anymore.",
        "premium.faq.transfer.title": "Can I transfer my premium subscription to another server?",
        "premium.faq.transfer.text": "Yes. Once you are subscribed, you'll be able to transfer your subscription to another server of yours {link}.",
        "premium.faq.transfer.link": "from this page",
        "premium.modal.defaultTitle": "You discovered a Premium feature!",
        "premium.modal.defaultSubtitle": "Upgrading to MEE6 Premium will unlock it.",
        "premium.modal.unlock": "Unlock PREMIUM",
        "premium.modal.notNow": "Not now",
        "premium.prices.billedYearly": "Billed yearly",
        "premium.prices.contact": "Contact us",
        "premium.prices.faq": "Frequently Asked Questions",
        "premium.prices.forever": "forever",
        "premium.prices.month": "month",
        "premium.prices.oneTime": "One-time payment",
        "premium.prices.perks": "Premium Perks",
        "premium.prices.select": "Select",
        "premium.prices.terms": "Terms & conditions",
        "premium.prices.year": "year",
        "premium.manage.title": "Manage your subscription",
        "premium.manage.paidBy": "Paid by",
        "premium.manage.actions": "Actions",
        "premium.manage.transfer": "Transfer subscription to another server",
        "premium.manage.manage": "Manage subscription",
        "premium.manage.active": "Active",
        "premium.manage.cancelled": "Cancelled",
        "premium.manage.nonRenewing": "Non renewing",
        "premium.manage.legacy": "You have a legacy account, please contact support for questions related to your subscription.",
        "premium.manage.notOwner": "Only the person paying for the subscription can manage it.",
        "premium.manage.switch": "Switch plan",
        "premium.manage.modal.title": "Switch plan",
        "premium.manage.modal.description": "This feature is temporarily disabled, please contact support to switch plan.",
        "premium.manage.modal.sendEmail": "Send an email",
        "premium.manage.modal.joinSupportServer": "Join support server",
        "premium.checkout.why": "Why choose premium?",
        "premium.checkout.continue": "Continue To Payment",
        "premium.renew.subscription.button": "Re-Subscribe",
        "premium.subscriptionEndsOn": "Subscription ends on {date}",
        "premium.subscription.cancelled": "Subscription cancelled",
        "premium.transfer.title": "Transfer Premium Subscription",
        "premium.transfer.description": "From here you can transfer your premium subscriptions between servers you manage. This is particularly useful if you deleted your premium server, or if you enabled premium on the wrong server.",
        "premium.transfer.warning": "Use this with caution: you can only transfer a subscription ONCE!",
        "premium.transfer.origin": "Origin Server",
        "premium.transfer.destination": "Destination Server",
        "premium.transfer.button": "Transfer",
        "premium.transfer.success": "Your subscription has been successfully transferred!",
        "premium.transfer.once": "You can only transfer this subscription ONCE!",
        "rankCard.background.access": "Get access to cool backgrounds, and even upload your own!",
        "rankCard.background.unlock": "Unlock for {price}",
        "rankCard.modal.title": "Edit Rank Card",
        "rankCard.modal.color": "Colors",
        "rankCard.modal.background": "Custom Background",
        "rankCard.modal.nav.customization": "Customize",
        "rankCard.modal.nav.visibility": "Visibility",
        "rankCard.getPro": "Get MEE6 Pro",
        "rankCard.getPro.description": "Get access to cool backgrounds and a 50% XP boost!",
        "role.searchCreate.placeholder": "Search or Create Role",
        "role.searchCreate.pickColor": "Pick a color",
        "role.searchCreate.createRole": "Create Role",
        "role.select.placeholder": "Select a role to reward",
        "role.select.missingPosition": "Whoops, it looks like I can't give one of the roles listed here. Please fix that by putting my role above all the roles listed here.",
        "role.select.missingManageRoles": "Whoops, it looks like I can't give any roles. Please fix that by giving me the MANAGE ROLES or ADMINISTRATOR permissions.",
        "select.guildPlaceholder": "Please select a server",
        "select.defaultPlaceholder": "Please select a value",
        "settings.botMaster.adminRoles": "Administrator Roles",
        "settings.botMaster.additionalRoles": "Additional Bot Master Roles",
        "settings.botMaster.heading": "Bot Masters",
        "settings.botMaster.description1": "Bot masters can access your Dashboard and edit every command and plugin configuration.",
        "settings.botMaster.description2": "Bot masters also bypass command role checks, are automatically considered moderators in the Moderator plugin and can reset anyone's XP in the Levels plugin!",
        "settings.botMaster.default": "Below are the roles that have the Administrator permission in your server. By default, any role with the Administrator permission is considered as a bot master.",
        "settings.botMaster.additional": "You can add roles below that will also be considered as bot masters, even if they do not have the Administrator permission.",
        "settings.language.description": "Change the default language of MEE6 in your server.",
        "settings.language.bot": "Bot language",
        "settings.language.heading": "Language",
        "settings.timezone.heading": "Timezone",
        "settings.timezone.bot": "Bot timezone",
        "settings.timezone.description": "Change the default timezone of MEE6 in your server.",
        "settings.prefix.heading": "Commands",
        "settings.prefix.bot": "Commands prefix",
        "settings.prefix.description": "You can change the prefix used to trigger the bot.",
        "sublist.confirmationModal.title": "Are you sure?",
        "sublist.confirmationModal.content": "This action is strictly irreversible!",
        "tutorials.title": "Tutorials",
        "tutorials.toc": "Table of contents",
        "tutorials.relatedArticles": "Related articles",
        "unauthorized.title": "Oops, looks like you can't do that",
        "welcome.title": "Welcome to MEE6's website!",
        "welcome.pleaseLogin": "Please login to proceed...",
        "welcome.loginWithDiscord": "Login with Discord",
        "welcomeCardBackgroundSelector.uploadImage": "+ Upload image",
        "welcomeCardBackgroundSelector.crop": "Crop",
        "welcomeCardBackgroudSelector.uploading": "Uploading...",
        "changelogModal.button.ok": "Got it, thanks!",
        "customBot.avatar": "Avatar",
        "customBot.heading": "Custom Bot™",
        "customBot.username": "Username",
        "customBot.title": "Customize your bot",
        "customBot.disable": "Disable custom bot",
        "customBot.description": "Here you can customize your bot by changing its username, avatar and activity.",
        "customBot.updateImage": "Update Image",
        "customBot.modal.next": "Next",
        "customBot.modal.title": "Setup your custom bot",
        "customBot.modal.description": "We need you to setup a custom bot on Discord's website and to paste its token here. With the token, you'll be able to change your bot's avatar and username.",
        "customBot.modal.token": "Your bot token",
        "customBot.modal.tokenPlaceholder": "Enter your bot token here...",
        "customBot.modal.howto": "How do I get my custom bot token?",
        "customBot.status.type": "Activity Type",
        "customBot.status.none": "None",
        "customBot.status.game": "Playing",
        "customBot.status.streaming": "Streaming",
        "customBot.status.listening": "Listening",
        "customBot.status.custom": "Custom",
        "customBot.status.text": "Activity text",
        "customBot.status.url": "Stream URL",
        "customBot.status.prefix.game": "Playing",
        "customBot.status.prefix.streaming": "Streaming",
        "customBot.status.prefix.listening": "Listening to",
        "customBot.status.wait": "Your new status will be visible in discord within a few minutes (max 1h).",
        "customBot.warning": "Please make sure not to use Custom Bots for anything that would break the Discord Terms of Service. This would result in your bot being temporarily or permanently blocked.",
        "customBot.blocked": "Your bot has been flagged by Discord anti-spam system for abusive behavior, visit {link} to open a ticket.",
        "customBot.blocked.acknowledge": "Remove warning",
        "guildEmbeds.description.placeholder": "Insert a short description",
        "guildEmbed.yourEmbeds": "{count, plural, =0 {Your Embed message} one {Your Embed message} other {Your Embed messages}}",
        "guildEmbeds.messageWarning": "Could not load the embed! Either the bot is missing read and read history permissions or the message has been deleted!",
        "plugins.guildEmbeds.longDescription": "You can send and manage special embed messages through the embed plugin",
        "plugins.guildEmbeds.new": "New Embed",
        "plugins.guildEmbeds.addMore": "Add more",
        deletedChannel: "#deleted-channel",
        "plugins.guildEmbeds.premium1": "With MEE6 Premium, you can send and manage more than one Embed message.",
        "plugins.guildEmbeds.premium2": "You'll also get awesome perks such as role rewards, advanced logging, and much more!",
        unknownUser: "Unknown User",
        "proCheckout.title": "MEE6 Pro",
        "proCheckout.description": "Customize your <span>rank card background</span> and get <span>50% more XP</span> on all the servers you are in!",
        "proCheckout.continue": "Continue to payment",
        "pluginCategories.social.name": "Social Connectors",
        "pluginCategories.fun.name": "Engagement & Fun",
        "pluginCategories.utilities.name": "Utilities & Management",
        "plugins.birthdays.command.birthday.description": "Show your birthday or another user's birthday",
        "plugins.birthdays.command.forget-birthday.description": "Remove your birthday",
        "plugins.birthdays.command.next-birthdays.description": "List up to 10 upcoming birthdays",
        "plugins.birthdays.command.remember-birthday.description": "Add your birthday",
        "plugins.birthdays.command.set-user-birthday.description": "Add another user's birthday",
        "plugins.birthdays.command.unset-user-birthday.description": "Remove another user's birthday",
        "plugins.birthdays.description": "Wish users' birthdays in a pre-defined channel",
        "plugins.birthdays.name": "Birthdays",
        "plugins.birthdays.roles.heading": "Birthday Role",
        "plugins.birthdays.roles.text": "MEE6 can attribute a role to users celebrating their birthday. Please check your role hierarchy and MEE6 permissions. Roles that can't be attributed will be removed from here.",
        "plugins.birthdays.roles.text2": "Use with caution: MEE6 will remove this role from all of the other users who are not celebrating their birthday. It is advised to use a dedicated role for this feature.",
        "plugins.birthdays.wish.channel": "Happy Birthday Wishing Channel",
        "plugins.birthdays.wish.heading": "Birthday Message",
        "plugins.birthdays.wish.hour": "Happy Birthday Wishing Hour",
        "plugins.birthdays.wish.hour.placeholder": "Please select a time...",
        "plugins.birthdays.wish.hour.timezone.change": "Change it here.",
        "plugins.birthdays.wish.message": "Happy Birthday Wishing Message",
        "plugins.birthdays.wish.message.age": "Happy Birthday Wishing Message with age",
        "plugins.birthdays.wish.message.age.description": "Applicable only if the member input their year of birth, if year usage is allowed.",
        "plugins.birthdays.wish.message.age.hint": "The age of the user",
        "plugins.birthdays.wish.message.description": "One message for each member having their birthday will be posted.",
        "plugins.birthdays.wish.text": "MEE6 can remember users' birthdays and wish them a happy one in a specific channel. The messages will be sent with respect to the timezone of your server.",
        "plugins.birthdays.year.allowed.title": "Allowed year usage",
        "plugins.birthdays.year.heading": "Birthday Year",
        "plugins.birthdays.year.mandatory.title": "Mandatory year usage",
        "plugins.birthdays.year.text": "MEE6 can allow or force users to use a birthday year.",
        "plugins.statistics.basic.add": "Add a new counter",
        "plugins.statistics.basic.bots.name": "Bots",
        "plugins.statistics.basic.count.explain": "Only {kind} and {count} are supported here. Only {count} is required.",
        "plugins.statistics.basic.description": "Count channels, members and roles for your server. Only 8 basic counters can be created, and only one per kind.",
        "plugins.statistics.basic.heading": "Basic counters",
        "plugins.statistics.basic.humans.name": "Humans",
        "plugins.statistics.basic.online_members.name": "Online Members",
        "plugins.statistics.basic.peak_online.name": "Peak Online",
        "plugins.statistics.basic.placeholder": "Select a kind...",
        "plugins.statistics.basic.text_channels.name": "Text Channels",
        "plugins.statistics.basic.total_channels.name": "Total Channels",
        "plugins.statistics.basic.total_members.name": "Total Members",
        "plugins.statistics.basic.total_roles.name": "Total Roles",
        "plugins.statistics.basic.voice_channels.name": "Voice Channels",
        "plugins.statistics.deleted.channel": "deleted-channel",
        "plugins.statistics.deleted.role": "deleted role",
        "plugins.statistics.description": "Display statistics about your server in the sidebar",
        "plugins.statistics.discord.name": "Discord channel name",
        "plugins.statistics.name": "Statistics",
        "plugins.statistics.role.add": "Add a new role",
        "plugins.statistics.role.count.explain": "Only {role_name} and {count} are supported here. Only {count} is required.",
        "plugins.statistics.roles.description": "Count members with selected roles. Only 8 role counters can be created, and only one per role.",
        "plugins.statistics.roles.heading": "Roles counters",
        "plugins.statistics.social.count.explain": "Only {account_name} and {count} are supported here. Only {count} is required.",
        "plugins.statistics.text": "MEE6 can count your server channels, members and roles, and also followers on multiple Twitch, Twitter and YouTube accounts. The counters update every 20 minutes.",
        "plugins.statistics.text2": "The results will be displayed in the name of locked voice channels, directly in the sidebar of your server. Removing a channel or a role on Discord removes its counter here.",
        "plugins.statistics.twitch.add": "Add a new channel",
        "plugins.statistics.twitch.description": "Count followers for selected Twitch channels. Only 8 total social counters (over all networks) can be created, and only one per account. Choose wisely!",
        "plugins.statistics.twitch.heading": "Twitch counters",
        "plugins.statistics.twitch.unknown": "Unknown Twitch Channel",
        "plugins.statistics.twitter.add": "Add a new user",
        "plugins.statistics.twitter.description": "Count followers for selected Twitter users. Only 8 total social counters (over all networks) can be created, and only one per account. Choose wisely!",
        "plugins.statistics.twitter.heading": "Twitter counters",
        "plugins.statistics.twitter.unknown": "Unknown Twitter User",
        "plugins.statistics.youtube.add": "Add a new channel",
        "plugins.statistics.youtube.description": "Count subscribers for selected YouTube channels. Only 8 total social counters (over all networks) can be created, and only one per account. Choose wisely!",
        "plugins.statistics.youtube.heading": "YouTube counters",
        "plugins.statistics.youtube.title": "YouTube",
        "plugins.statistics.youtube.unknown": "Unknown YouTube Channel",
        "onboarding.welcome": "Welcome to MEE6",
        "onboarding.choosePlan": "MEE6 has been added to your server. Choose a plan to continue.",
        "onboarding.basicPlan.title": "Basic plan",
        "onboarding.basicPlan.price": "Free",
        "onboarding.basicPlan.description": "Great for trying out MEE6 or for very small servers",
        "onboarding.basicPlan.feature1": "All basic features",
        "onboarding.basicPlan.feature2": "MEE6 branding",
        "onboarding.basicPlan.feature3": "No social connectors",
        "onboarding.basicPlan.feature4": "Basic leveling",
        "onboarding.basicPlan.feature5": "Basic moderation",
        "onboarding.premium.title": "Premium",
        "onboarding.premium.price": "Starting at {price}/mo",
        "onboarding.premium.description": "Recommended if you want to build a professional server.",
        "onboarding.premium.feature1": "All features unlocked",
        "onboarding.premium.feature2": "Custom bot",
        "onboarding.premium.feature3": "Unlimited social connectors",
        "onboarding.premium.feature4": "Advanced moderation",
        "onboarding.premium.feature5": "Advanced leveling",
        "onboarding.premium.feature6": "... and a lot more",
        "onboarding.continue": "Continue",
        "settings.slashCommands": "Slash Commands",
        "settings.slashCommands.enable": "Enable slash commands",
        "badge.beta": "Beta"
    };
export {
    t as
    default, e as deletedChannel, o as unknownUser
};
